#!/bin/bash


<<comment
this is script installs any package passed as an argument.
 Usage: ./install_package.sh <package_name>

comment

 echo "************* INSTALLING $1 ***************"
 sudo apt-get update
 sudo apt-get install $1 -y
 sudo systemctl start $1
 sudo systemctl enable $1
 echo "************* INSTALLED $1 ****************"
